### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Bariona** [felpzOliveira/Bubbles#1] opened 2024-05-28 09:52 UTC
While running the commands below:
```
mkdir build
cd build
cmake -DCONVEXHULL_QHULL=OFF ..
make -j4
```

after entering `cmake -DCONVEXHULL_QHULL=OFF ..`, there is an error showing that:

```
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
checkcuda.cu
  正在创建库 path-to-project\Bubbles\build\checkcuda.lib 和对象 path-to-project\Bubbles\build\checkcuda.exp
-- Release build
-- CUDA Architecture: sm_86
CMake Error at CMakeLists.txt:75 (add_subdirectory):
  The source directory

    path-to-project/Bubbles/src/third/gDel3D

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```
wondering how to fix it?

**Comment by felpzOliveira** [comment] 2024-05-28 15:32
Hello @Bariona ,
It is likely that the issue is because of the current versioning of the gDel3D module. There is some working being done with this module and it is likely it broke compilation. Because the usage of gDel3D is currently being worked on I'm gonna removed it from the master branch.

Can you retry with the latest commit (844dc71661d26d828dcfd9002a0b6e9ab01130b4)?

Also, if you can, use this code in Linux. The source has never been tested on Windows and it is likely to have issues and there is currently no plans to make it work under both systems.

**Comment by Bariona** [comment] 2024-05-29 04:43
Ok! Also I want to ask what can `<bubbles_output>` be in the README file. 

It seems that there are some hard-coded paths in the project such as `UtilSetGlobalModelPath("/home/felpz/Documents/CGStuff/models");` shown in `src\bubbles.cpp`, could you provide those files? 

Thanks.

**Comment by felpzOliveira** [comment] 2024-05-29 12:36
Things marked as `<bubbles_output>` are simulations files generated as simulations are performed. I believe the resources folder has some files for example, I'll add two more just in case (76f72b3). These have 2 formats:

- a XYZ-like file where the first line specify the amount of particles and than each line contains information per-particle, it usually referred as `legacy` in command line arguments. These were not supposed to continue to work but it turned out it is useful to have a simple description to use with other software ;

- a section-like file where multiple blocks of information are delimited by specific tokens.

Because we don't support any type of description language, simulations need to be specified in C/C++ within the code itself, as it was not meant for distribution. Some simulations, all located under `tests`, use OBJ/PLY models to setup scenes as colliders or emitters. In order to make things a tiny bit better there are functions like the one you pointed that can globally set a path to find models.

As people were constantly just changing the code for themselves we never actually added command line support on the simulator itself, so we end with this hardcoded path (sorry for that).

If you are trying to run a specific simulation I can check if I can give you the required model for it, but this folder contains some models that have some licensing issues so I can't just give them.

If you are only interested in boundary stuff than you should be fine running `bbtool` and not caring about the simulations binary (and paths, etc...).

**Closed as completed** 2024-06-11 14:38 UTC
